services:
  app:
    image: node:22
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '8080:8080'
    command: yarn start
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/organic-soft

  mongo:
    image: mongo
    ports:
      - '27017:27017'
